import streamlit as st
from logging_config import log_exception
import pandas as pd
from sqlalchemy import text
from database.database import engine
from auth import require_login

user = require_login()
role = user["Role"]

st.caption(f"Welcome, {user['FullName']} · {role}")


def get_available_funds():
    with engine.begin() as connection:
        connection.execute(text("""
                CREATE TABLE IF NOT EXISTS "BankTransactions" (
                    "BankTransactionID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "CashDrawerID" BIGINT NULL,
                    "UserID" BIGINT NOT NULL,
                    "TransactionType" VARCHAR(50) NOT NULL,
                    "Amount" NUMERIC(18, 2) NOT NULL CHECK ("Amount" > 0),
                    "Reason" VARCHAR(500),
                    "TransactionDateTime" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """))
        balances = connection.execute(text("""
                WITH drawers AS (
                    SELECT DISTINCT ON ("UserID")
                        "CashDrawerID",
                        "UserID",
                        "OpenDateTime",
                        "OpeningCash"
                    FROM "CashDrawers"
                    WHERE "Status" = 'Open'
                    ORDER BY "UserID", "CashDrawerID" DESC
                ),
                drawer_balances AS (
                    SELECT
                        COALESCE(
                            d."OpeningCash"
                            + COALESCE((
                                SELECT SUM(s."GrandTotal")
                                FROM "Sales" AS s
                                WHERE s."UserID" = d."UserID"
                                  AND s."PaymentMode" = 'Cash'
                                  AND s."SaleDate" >= d."OpenDateTime"
                            ), 0)
                            + COALESCE((
                                SELECT SUM(
                                    CASE
                                        WHEN ct."TransactionType" = 'Cash In'
                                            THEN ct."Amount"
                                        ELSE -ct."Amount"
                                    END
                                )
                                FROM "CashTransactions" AS ct
                                WHERE ct."CashDrawerID" = d."CashDrawerID"
                                  AND ct."TransactionType" IN ('Cash In', 'Expense', 'Cash Out')
                            ), 0),
                            0
                        ) AS "CashInHand",
                        GREATEST(
                            0,
                            COALESCE((
                                SELECT SUM(s."GrandTotal")
                                FROM "Sales" AS s
                                WHERE s."UserID" = d."UserID"
                                  AND s."PaymentMode" IN ('UPI', 'Card')
                                  AND s."SaleDate" >= d."OpenDateTime"
                            ), 0)
                            + COALESCE((
                                SELECT SUM(
                                    CASE
                                        WHEN bt."TransactionType" = 'Bank Deposit'
                                            THEN bt."Amount"
                                        ELSE -bt."Amount"
                                    END
                                )
                                FROM "BankTransactions" AS bt
                                WHERE bt."UserID" = d."UserID"
                                  AND bt."TransactionDateTime" >= d."OpenDateTime"
                                  AND bt."TransactionType" IN ('Bank Deposit', 'Bank Withdrawal')
                            ), 0)
                        ) AS "CashInBank"
                    FROM drawers AS d
                )
                SELECT
                    COALESCE(SUM("CashInHand"), 0) AS "CashInHand",
                    COALESCE(SUM("CashInBank"), 0) AS "CashInBank"
                FROM drawer_balances
            """)).mappings().one()

    return float(balances["CashInHand"]), float(balances["CashInBank"])


st.subheader("Cash position across all users")
try:
    cash_in_hand, cash_in_bank = get_available_funds()
    cash_col, bank_col = st.columns(2)
    cash_col.metric("Cash in hand", f"₹{cash_in_hand:,.2f}", border=True)
    bank_col.metric("Cash in bank", f"₹{cash_in_bank:,.2f}", border=True)
    st.caption("Totals include each user's latest open cash drawer.")
except Exception as e:
    st.error("Unable to load cash and bank balances.")
    log_exception(e)
    st.exception(e)


# =========================================================
# SALES BOY DASHBOARD
# =========================================================

if role == "Sales Boy":

    try:
        with engine.connect() as connection:

            sales = (
                connection.execute(
                    text("""
                    SELECT
                        COUNT(*) AS "TotalBills",
                        COALESCE(SUM("GrandTotal"), 0) AS "TotalSales"
                    FROM "Sales"
                    WHERE CAST("SaleDate" AS DATE) = CURRENT_DATE
                      AND "UserID" = :user_id
                """),
                    {"user_id": user["UserID"]},
                )
                .mappings()
                .first()
            )

        st.subheader("Your activity today")
        c1, c2 = st.columns(2)

        c1.metric(
            "My Sales Today",
            f"₹{float(sales['TotalSales'] or 0):,.2f}",
            border=True,
        )

        c2.metric(
            "Bills today",
            int(sales["TotalBills"] or 0),
            border=True,
        )

        st.info("Use Billing to create a new bill.")

    except Exception as e:
        st.error("Unable to load your sales dashboard.")
        log_exception(e)
        st.exception(e)


# =========================================================
# MANAGER / ADMIN DASHBOARD
# =========================================================

else:

    try:

        with engine.connect() as connection:

            # ---------------------------------------------
            # Today's Sales
            # ---------------------------------------------

            sales = connection.execute(text("""
                    SELECT
                        COUNT(*) AS "TotalBills",
                        COALESCE(SUM("GrandTotal"), 0) AS "TotalSales"
                    FROM "Sales"
                    WHERE CAST("SaleDate" AS DATE) = CURRENT_DATE
                """)).mappings().first()

            # ---------------------------------------------
            # Product Count
            # ---------------------------------------------

            product_count = connection.execute(text("""
                    SELECT COUNT(*) AS "ProductCount"
                    FROM "Products"
                """)).scalar()

            # ---------------------------------------------
            # Low Stock Count
            # ---------------------------------------------

            low_stock_count = connection.execute(text("""
                    SELECT COUNT(*) AS "LowStock"
                    FROM "Products"
                    WHERE COALESCE("Stock", 0) <= 10
                """)).scalar()

        st.subheader("Today's overview")
        c1, c2, c3, c4 = st.columns(4)

        c1.metric(
            "Today's Sales",
            f"₹{float(sales['TotalSales'] or 0):,.2f}",
            border=True,
        )

        c2.metric(
            "Today's Bills",
            int(sales["TotalBills"] or 0),
            border=True,
        )

        c3.metric(
            "Products",
            int(product_count or 0),
            border=True,
        )

        c4.metric(
            "Low Stock",
            int(low_stock_count or 0),
            border=True,
        )

        low_stock_column, payment_column = st.columns([1.2, 1])
        with low_stock_column:
            st.subheader("Low stock products")

            low_stock = pd.read_sql(
                text("""
                    SELECT
                        "ProductID",
                        "ProductName",
                        "Barcode",
                        "Stock",
                        "SellingPrice"
                    FROM "Products"
                    WHERE COALESCE("Stock", 0) <= 10
                    ORDER BY "Stock" ASC, "ProductName"
                """),
                engine,
            )

            if low_stock.empty:
                st.success("No low-stock products.")
            else:
                with st.container(border=True):
                    st.dataframe(low_stock, width="stretch", hide_index=True)

        with payment_column:
            st.subheader("Payment summary")
            payment_summary = pd.read_sql(
                text("""
                    SELECT
                        "PaymentMode",
                        COUNT(*) AS "Bills",
                        COALESCE(SUM("GrandTotal"), 0) AS "Amount"
                    FROM "Sales"
                    WHERE CAST("SaleDate" AS DATE) = CURRENT_DATE
                    GROUP BY "PaymentMode"
                    ORDER BY "PaymentMode"
                """),
                engine,
            )

            if payment_summary.empty:
                st.info("No sales recorded today.")
            else:
                with st.container(border=True):
                    st.dataframe(payment_summary, width="stretch", hide_index=True)

    except Exception as e:

        st.error("Unable to load dashboard data.")
        log_exception(e)
        st.exception(e)
