from datetime import date



import pandas as pd

import streamlit as st

from sqlalchemy import text



from auth import require_role

from database.database import engine

from logging_config import log_exception



st.set_page_config(page_title="Employees", page_icon="👥", layout="wide")

require_role("Admin")





def ensure_employee_table():

    with engine.begin() as connection:

        connection.execute(
            text("""
                CREATE TABLE IF NOT EXISTS "Employees" (
                    "EmployeeID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "FullName" VARCHAR(150) NOT NULL,
                    "Phone" VARCHAR(32),
                    "Address" VARCHAR(500),
                    "JobTitle" VARCHAR(100),
                    "HireDate" DATE NOT NULL,
                    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                    "UserID" INTEGER,
                    "CreatedDate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT "FK_Employees_Users"
                        FOREIGN KEY ("UserID")
                        REFERENCES "Users" ("UserID")
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "UX_Employees_UserID"
                ON "Employees" ("UserID")
                WHERE "UserID" IS NOT NULL;
            """)
        )


def load_employees():
    return pd.read_sql(
        text("""
            SELECT
                e."EmployeeID",
                e."FullName",
                e."Phone",
                e."Address",
                e."JobTitle",
                e."HireDate",
                e."IsActive",
                e."UserID",
                u."Username",
                u."Role"
            FROM "Employees" AS e
            LEFT JOIN "Users" AS u
                ON u."UserID" = e."UserID"
            ORDER BY e."FullName", e."EmployeeID"
        """),
        engine,
    )


def load_users():
    return pd.read_sql(
        text("""
            SELECT
                "UserID",
                "Username",
                "FullName",
                "Role",
                "IsActive"
            FROM "Users"
            ORDER BY "FullName", "Username"
        """),
        engine,
    )


def account_options(users, employees, current_employee_id=None):

    linked_user_ids = {

        int(user_id)

        for employee_id, user_id in zip(

            employees["EmployeeID"], employees["UserID"]

        )

        if pd.notna(user_id) and employee_id != current_employee_id

    }

    options = {"No linked user account": None}



    for user in users.itertuples(index=False):

        user_id = int(user.UserID)

        if user_id in linked_user_ids:

            continue



        status = "active" if bool(user.IsActive) else "inactive"

        label = f"{user.Username} - {user.FullName} ({user.Role}, {status})"

        options[label] = user_id



    return options





def save_employee(
    employee_id,
    full_name,
    phone,
    address,
    job_title,
    hire_date,
    is_active,
    user_id,
):
    values = {
        "full_name": full_name.strip(),
        "phone": phone.strip() or None,
        "address": address.strip() or None,
        "job_title": job_title.strip() or None,
        "hire_date": hire_date,
        "is_active": is_active,
        "user_id": user_id,
    }

    with engine.begin() as connection:

        if employee_id is None:

            connection.execute(
                text("""
                    INSERT INTO "Employees"
                        ("FullName", "Phone", "Address", "JobTitle",
                         "HireDate", "IsActive", "UserID")
                    VALUES
                        (:full_name, :phone, :address, :job_title,
                         :hire_date, :is_active, :user_id)
                """),
                values,
            )

        else:

            values["employee_id"] = int(employee_id)

            connection.execute(
                text("""
                    UPDATE "Employees"
                    SET
                        "FullName" = :full_name,
                        "Phone" = :phone,
                        "Address" = :address,
                        "JobTitle" = :job_title,
                        "HireDate" = :hire_date,
                        "IsActive" = :is_active,
                        "UserID" = :user_id
                    WHERE "EmployeeID" = :employee_id
                """),
                values,
            )


try:

    ensure_employee_table()

    employees = load_employees()

    users = load_users()

except Exception as error:

    log_exception(error)

    st.error("Could not load employee profiles. Check the database connection and permissions.")

    st.stop()



st.title("Employees")

st.caption("Maintain employee profiles and optionally link them to POS user accounts.")



active_count = int(employees["IsActive"].sum()) if not employees.empty else 0

linked_count = int(employees["UserID"].notna().sum()) if not employees.empty else 0

metric_active, metric_linked, metric_total = st.columns(3)

metric_active.metric("Active employees", active_count)

metric_linked.metric("Linked user accounts", linked_count)

metric_total.metric("Total profiles", len(employees))



st.subheader("Add employee")

with st.form("add_employee_form", clear_on_submit=True):

    name_col, title_col = st.columns(2)

    full_name = name_col.text_input("Full name")

    job_title = title_col.text_input("Job title")



    phone_col, hire_date_col, account_col = st.columns(3)

    phone = phone_col.text_input("Phone")

    hire_date = hire_date_col.date_input("Hire date", value=date.today())

    add_accounts = account_options(users, employees)

    account_label = account_col.selectbox(

        "Linked user account",

        list(add_accounts),

    )



    address = st.text_area("Address")

    add_submitted = st.form_submit_button(

        "Create employee",

        type="primary",

        width="stretch",

    )



if add_submitted:

    if not full_name.strip():

        st.warning("Enter the employee's full name.")

    else:

        try:

            save_employee(

                None,

                full_name,

                phone,

                address,

                job_title,

                hire_date,

                True,

                add_accounts[account_label],

            )

            st.success("Employee profile created.")

            st.rerun()

        except Exception as error:

            log_exception(error)

            st.error("Could not create employee profile. The selected user may already be linked.")



st.divider()

st.subheader("Employee directory")

search_col, status_col = st.columns([2, 1])

search = search_col.text_input("Search employees", placeholder="Name, phone, or job title")

status_filter = status_col.selectbox("Status", ["All", "Active", "Inactive"])



visible_employees = employees.copy()

if search.strip():

    searchable = visible_employees[

        ["FullName", "Phone", "JobTitle"]

    ].fillna("").astype(str)

    matches = searchable.apply(

        lambda column: column.str.contains(search.strip(), case=False, regex=False)

    ).any(axis=1)

    visible_employees = visible_employees[matches]

if status_filter == "Active":

    visible_employees = visible_employees[visible_employees["IsActive"]]

elif status_filter == "Inactive":

    visible_employees = visible_employees[~visible_employees["IsActive"]]



if visible_employees.empty:

    st.info("No employee profiles match these filters.")

else:

    directory = visible_employees[

        ["FullName", "JobTitle", "Phone", "HireDate", "Username", "Role", "IsActive"]

    ].rename(

        columns={

            "FullName": "Employee",

            "JobTitle": "Job title",

            "Phone": "Phone",

            "HireDate": "Hire date",

            "Username": "Linked account",

            "Role": "Account role",

            "IsActive": "Active",

        }

    )

    st.dataframe(directory, hide_index=True, width="stretch")



    st.divider()

    st.subheader("Edit employee")

    employee_labels = {

        f"{row.FullName} (ID {int(row.EmployeeID)})": int(row.EmployeeID)

        for row in visible_employees.itertuples(index=False)

    }

    selected_label = st.selectbox("Select employee", list(employee_labels))

    selected_id = employee_labels[selected_label]

    selected = employees[employees["EmployeeID"] == selected_id].iloc[0]

    edit_accounts = account_options(users, employees, selected_id)

    linked_user_id = int(selected["UserID"]) if pd.notna(selected["UserID"]) else None

    selected_account_label = next(

        label

        for label, user_id in edit_accounts.items()

        if user_id == linked_user_id

    )



    with st.form(f"edit_employee_{selected_id}"):

        edit_name_col, edit_title_col = st.columns(2)

        edit_name = edit_name_col.text_input(

            "Full name",

            value=str(selected["FullName"]),

        )

        edit_job_title = edit_title_col.text_input(

            "Job title",

            value=str(selected["JobTitle"] or ""),

        )



        edit_phone_col, edit_date_col, edit_account_col = st.columns(3)

        edit_phone = edit_phone_col.text_input(

            "Phone",

            value=str(selected["Phone"] or ""),

        )

        current_hire_date = pd.to_datetime(selected["HireDate"]).date()

        edit_hire_date = edit_date_col.date_input(

            "Hire date",

            value=current_hire_date,

        )

        edit_account_label = edit_account_col.selectbox(

            "Linked user account",

            list(edit_accounts),

            index=list(edit_accounts).index(selected_account_label),

        )

        edit_address = st.text_area(

            "Address",

            value=str(selected["Address"] or ""),

        )

        edit_active = st.checkbox("Employee active", value=bool(selected["IsActive"]))

        edit_submitted = st.form_submit_button(

            "Save changes",

            type="primary",

            width="stretch",

        )



    if edit_submitted:

        if not edit_name.strip():

            st.warning("Enter the employee's full name.")

        else:

            try:

                save_employee(

                    selected_id,

                    edit_name,

                    edit_phone,

                    edit_address,

                    edit_job_title,

                    edit_hire_date,

                    edit_active,

                    edit_accounts[edit_account_label],

                )

                st.success("Employee profile updated.")

                st.rerun()

            except Exception as error:

                log_exception(error)

                st.error("Could not update employee profile. The selected user may already be linked.")
