from datetime import date, datetime



import streamlit as st

from sqlalchemy import text



from auth import require_role

from database.database import engine

from logging_config import log_exception



# PAGE CONFIG

st.set_page_config(page_title="Purchase Stock", page_icon="📦", layout="wide")

st.markdown("""
<style>
.block-container { padding-top:.55rem !important; padding-bottom:.65rem !important; max-width:1500px; }
.compact-title { font-size:1.3rem; font-weight:700; margin:0 0 .25rem 0; }
.section-title { font-size:1rem; font-weight:700; margin:.3rem 0 .2rem 0; }
div[data-testid="stVerticalBlock"] { gap:.32rem !important; }
div[data-testid="stHorizontalBlock"] { gap:.5rem !important; }
hr { margin:.35rem 0 !important; }
div[data-testid="stWidgetLabel"] p { font-size:.7rem !important; margin-bottom:2px !important; }
div[data-testid="stTextInput"] input, div[data-testid="stNumberInput"] input { height:33px !important; min-height:33px !important; padding:3px 8px !important; font-size:.8rem !important; }
div[data-testid="stDateInput"] input { height:33px !important; min-height:33px !important; font-size:.8rem !important; }
.stButton > button { min-height:33px !important; height:33px !important; padding:3px 9px !important; font-size:.77rem !important; border-radius:7px !important; }
div[data-testid="stMetric"] { padding:5px 8px !important; border:1px solid #e2e8f0; border-radius:8px; }
div[data-testid="stMetricLabel"] { font-size:.66rem !important; }
div[data-testid="stMetricValue"] { font-size:.95rem !important; }
div[data-testid="stAlert"] { padding:.38rem .65rem !important; }
.stock-name { font-weight:700; font-size:.88rem; }
.stock-meta { color:#64748b; font-size:.7rem; }
</style>
<div class="compact-title">📦 Purchase Stock <span style="font-size:.7rem;font-weight:500;color:#64748b;">• Admin approval</span></div>
""", unsafe_allow_html=True)

user = require_role("Sales Boy","Manager")





# DATABASE CONNECTION

# Uses the shared PostgreSQL SQLAlchemy engine from database.database.

# DATABASE TEST

def test_database():

    try:

        # Use the shared PostgreSQL engine from database.database

        with engine.connect() as conn:

            conn.execute(text("SELECT 1"))

        return True, None

    except Exception as e:

        return False, str(e)





def get_available_funds():

    with engine.begin() as conn:

        conn.execute(text("""

                CREATE TABLE IF NOT EXISTS "BankTransactions" (

                    "BankTransactionID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                    "CashDrawerID" BIGINT NULL,

                    "UserID" BIGINT NOT NULL,

                    "TransactionType" VARCHAR(50) NOT NULL,

                    "Amount" NUMERIC(18, 2) NOT NULL CHECK ("Amount" > 0),

                    "Reason" VARCHAR(500),

                    "TransactionDateTime" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

                )

            """))

        balances = conn.execute(text("""

                WITH drawers AS (

                    SELECT DISTINCT ON ("UserID")

                        "CashDrawerID",

                        "UserID",

                        "OpenDateTime",

                        "OpeningCash"

                    FROM "CashDrawers"

                    WHERE "Status" = 'Open'

                    ORDER BY "UserID", "CashDrawerID" DESC

                ),

                drawer_balances AS (

                    SELECT

                        COALESCE(

                            d."OpeningCash"

                            + COALESCE((

                                SELECT SUM(s."GrandTotal")

                                FROM "Sales" AS s

                                WHERE s."UserID" = d."UserID"

                                  AND s."PaymentMode" = 'Cash'

                                  AND s."SaleDate" >= d."OpenDateTime"

                            ), 0)

                            + COALESCE((

                                SELECT SUM(

                                    CASE

                                        WHEN ct."TransactionType" = 'Cash In'

                                            THEN ct."Amount"

                                        ELSE -ct."Amount"

                                    END

                                )

                                FROM "CashTransactions" AS ct

                                WHERE ct."CashDrawerID" = d."CashDrawerID"

                                  AND ct."TransactionType" IN ('Cash In', 'Expense', 'Cash Out')

                            ), 0),

                            0

                        ) AS "CashInHand",

                        GREATEST(

                            0,

                            COALESCE((

                                SELECT SUM(s."GrandTotal")

                                FROM "Sales" AS s

                                WHERE s."UserID" = d."UserID"

                                  AND s."PaymentMode" IN ('UPI', 'Card')

                                  AND s."SaleDate" >= d."OpenDateTime"

                            ), 0)

                            + COALESCE((

                                SELECT SUM(

                                    CASE

                                        WHEN bt."TransactionType" = 'Bank Deposit'

                                            THEN bt."Amount"

                                        ELSE -bt."Amount"

                                    END

                                )

                                FROM "BankTransactions" AS bt

                                WHERE bt."UserID" = d."UserID"

                                  AND bt."TransactionDateTime" >= d."OpenDateTime"

                                  AND bt."TransactionType" IN ('Bank Deposit', 'Bank Withdrawal')

                            ), 0)

                        ) AS "CashInBank"

                    FROM drawers AS d

                )

                SELECT

                    COALESCE(SUM("CashInHand"), 0) AS "CashInHand",

                    COALESCE(SUM("CashInBank"), 0) AS "CashInBank"

                FROM drawer_balances

            """)).mappings().first()



    if not balances:

        return 0.0, 0.0

    return float(balances["CashInHand"]), float(balances["CashInBank"])





# FIND EXISTING PRODUCT

def find_product(barcode, product_name):

    barcode = (barcode or "").strip()

    product_name = (product_name or "").strip()

    if not barcode and not product_name:

        return None, None

    with engine.connect() as conn:

        # First check barcode

        if barcode:

            result = (

                conn.execute(

                    text("""

                    SELECT

                        "ProductID",

                        "ProductName",

                        "Barcode",

                        "SellingPrice",

                        "Stock",

                        "GSTPercent",

                        "PurchasePrice"

                    FROM "Products"

                    WHERE BTRIM("Barcode") = :barcode

                """),

                    {"barcode": barcode},

                )

                .mappings()

                .all()

            )

            if len(result) == 1:

                product = dict(result[0])

                return product, "Barcode"

            elif len(result) > 1:

                raise ValueError(f"Multiple products found with barcode " f"{barcode}.")

        # Then check product name

        if product_name:

            result = (

                conn.execute(

                    text("""

                    SELECT

                        "ProductID",

                        "ProductName",

                        "Barcode",

                        "SellingPrice",

                        "Stock",

                        "GSTPercent",

                        "PurchasePrice"

                    FROM "Products"

                    WHERE LOWER(BTRIM("ProductName"))

                        =

                          LOWER(BTRIM(:product_name))

                """),

                    {"product_name": product_name},

                )

                .mappings()

                .all()

            )

            if len(result) == 1:

                product = dict(result[0])

                return product, "Product Name"

            elif len(result) > 1:

                raise ValueError(

                    f"Multiple products found with name " f"{product_name}."

                )

    return None, None





# GENERATE TEMPORARY BATCH NUMBER

def generate_batch_number():

    now = datetime.now()

    return f"B{now.strftime('%Y%m%d%H%M%S%f')[:-3]}"





# SESSION STATE

if "stock_items" not in st.session_state:

    st.session_state.stock_items = []

if "barcode" not in st.session_state:

    st.session_state.barcode = ""

if "product_name" not in st.session_state:

    st.session_state.product_name = ""

if "quantity" not in st.session_state:

    st.session_state.quantity = 1.0

if "purchase_price" not in st.session_state:

    st.session_state.purchase_price = 0.0

if "selling_price" not in st.session_state:

    st.session_state.selling_price = 0.0

if "expiry_date" not in st.session_state:

    st.session_state.expiry_date = date.today()





# CLEAR PRODUCT FORM

def clear_product_form():

    st.session_state.barcode = ""

    st.session_state.product_name = ""

    st.session_state.quantity = 1.0

    st.session_state.purchase_price = 0.0

    st.session_state.selling_price = 0.0

    st.session_state.expiry_date = date.today()





# ADD STOCK

def add_stock():

    barcode = st.session_state.barcode.strip()

    product_name = st.session_state.product_name.strip()

    quantity = float(st.session_state.quantity)

    purchase_price = float(st.session_state.purchase_price)

    selling_price = float(st.session_state.selling_price)

    expiry_date = st.session_state.expiry_date

    # Validation

    if not product_name:

        st.session_state.match_message = "❌ Please enter Product Name."

        return

    if quantity <= 0:

        st.session_state.match_message = "❌ Quantity must be greater than zero."

        return

    if purchase_price < 0:

        st.session_state.match_message = "❌ Purchase price cannot be negative."

        return

    if selling_price < 0:

        st.session_state.match_message = "❌ Selling price cannot be negative."

        return

    # Find existing product

    try:

        product, match_type = find_product(barcode, product_name)

    except ValueError as e:

        st.session_state.match_message = f"❌ {str(e)}"

        return

    # Existing product

    if product:

        # Existing products: if the manager leaves prices at 0,

        # use the current product prices. A manually entered non-zero

        # price is preserved because batch prices may change.

        if purchase_price <= 0 and product.get("PurchasePrice") is not None:

            purchase_price = float(product["PurchasePrice"])

        if selling_price <= 0 and product.get("SellingPrice") is not None:

            selling_price = float(product["SellingPrice"])

        product_id = product["ProductID"]

        final_product_name = product["ProductName"]

        final_barcode = product["Barcode"]

        product_status = "EXISTING"

        match_message = (

            f"✅ Existing product found by "

            f"{match_type}: "

            f"{final_product_name} "

            f"(Product ID: {product_id})"

        )

    # New product

    else:

        product_id = None

        final_product_name = product_name

        final_barcode = barcode or None

        product_status = "NEW"

        match_message = "🆕 New product. " "Admin approval will create the product."

    # Generate batch number

    batch_number = generate_batch_number()

    # Purchase value

    purchase_value = quantity * purchase_price

    # Create staging item

    item = {

        "ProductID": product_id,

        "ProductName": final_product_name,

        "Barcode": final_barcode,

        "BatchNo": batch_number,

        "Quantity": quantity,

        "PurchasePrice": purchase_price,

        "SellingPrice": selling_price,

        "ExpiryDate": expiry_date,

        "PurchaseValue": purchase_value,

        "ProductStatus": product_status,

        "MatchType": match_type or "NEW",

    }

    st.session_state.stock_items.append(item)

    st.session_state.match_message = match_message

    # Clear form

    st.session_state.barcode = ""

    st.session_state.product_name = ""

    st.session_state.quantity = 1.0

    st.session_state.purchase_price = 0.0

    st.session_state.selling_price = 0.0

    st.session_state.expiry_date = date.today()





# REMOVE STOCK ITEM

def remove_stock_item(index):

    st.session_state.stock_items.pop(index)





# DATABASE STATUS

db_ok, db_error = test_database()

if db_ok:

    st.markdown("<span style='font-size:.72rem;color:#15803d;font-weight:600;'>● POSDB connected</span>", unsafe_allow_html=True)

    try:

        cash_in_hand, cash_in_bank = get_available_funds()

        available_funds = cash_in_hand + cash_in_bank

    except Exception as e:

        cash_in_hand = None

        cash_in_bank = None

        available_funds = None

        st.error("Unable to check your current cash and bank balances.")

        log_exception(e)

        st.exception(e)

else:

    cash_in_hand = None

    cash_in_bank = None

    available_funds = None

    st.error("🔴 POSDB connection failed")

    with st.expander("Show database error"):

        st.code(db_error)

st.divider()

# PRODUCT ENTRY

st.markdown('<div class="section-title">1. Add Stock</div>', unsafe_allow_html=True)

col1, col2, col3 = st.columns([1.05, 2.55, .8])
with col1:
    st.text_input("Barcode", key="barcode", placeholder="Scan barcode")
with col2:
    st.text_input("Product Name", key="product_name", placeholder="Enter product name")
with col3:
    st.markdown("<div style='height:21px'></div>", unsafe_allow_html=True)
    check_product_clicked = st.button("🔎 Check", width="stretch")

if check_product_clicked:
    barcode = st.session_state.barcode.strip()
    product_name = st.session_state.product_name.strip()
    if not barcode and not product_name:
        st.warning("Enter barcode or product name.")
    else:
        product, match_type = find_product(barcode, product_name)
        if product:
            st.success(f"Existing product found by {match_type.lower()}.")
            st.write(f"**Product:** {product['ProductName']}  •  **Barcode:** {product['Barcode'] or '-'}")
        else:
            st.warning("No matching product found. This will be treated as a NEW PRODUCT.")

col1, col2, col3, col4 = st.columns([1.0, 1.15, 1.15, 1.15])
with col1:
    st.number_input("Quantity", min_value=0.001, value=1.0, step=1.0, key="quantity")
with col2:
    st.number_input("Purchase Price", min_value=0.0, value=0.0, step=0.01, format="%.2f", key="purchase_price")
with col3:
    st.number_input("Selling Price", min_value=0.0, value=0.0, step=0.01, format="%.2f", key="selling_price")
with col4:
    st.date_input("Expiry Date", value=date.today(), key="expiry_date")

purchase_value = st.session_state.quantity * st.session_state.purchase_price
st.caption(f"Purchase Value: **₹{purchase_value:,.2f}**")

col1, col2 = st.columns([1.4, 1])
with col1:
    st.button("➕ Add Stock", type="primary", width="stretch", on_click=add_stock)
with col2:
    if st.button("Clear", width="stretch"):
        clear_product_form()
        st.rerun()

# MATCH MESSAGE

if "match_message" in st.session_state:

    st.info(st.session_state.match_message)

st.divider()





# STOCK ITEMS

# EDIT STOCK ITEM POPUP

@st.dialog("✏️ Edit Stock Item")

def edit_stock_item_dialog(index):

    item = st.session_state.stock_items[index]

    st.caption("Edit the stock item before submitting it for Admin approval.")

    col1, col2 = st.columns(2)

    with col1:

        edit_product_name = st.text_input(

            "Product Name",

            value=str(item.get("ProductName") or ""),

            key=f"edit_product_name_{index}",

        )

        edit_barcode = st.text_input(

            "Barcode",

            value=str(item.get("Barcode") or ""),

            key=f"edit_barcode_{index}",

        )

        edit_batch_no = st.text_input(

            "Batch Number",

            value=str(item.get("BatchNo") or ""),

            key=f"edit_batch_no_{index}",

        )

    with col2:

        edit_quantity = st.number_input(

            "Quantity",

            min_value=0.001,

            value=float(item.get("Quantity") or 0.001),

            step=1.0,

            format="%.3f",

            key=f"edit_quantity_{index}",

        )

        edit_purchase_price = st.number_input(

            "Purchase Price",

            min_value=0.0,

            value=float(item.get("PurchasePrice") or 0.0),

            step=0.01,

            format="%.2f",

            key=f"edit_purchase_price_{index}",

        )

        edit_selling_price = st.number_input(

            "Selling Price",

            min_value=0.0,

            value=float(item.get("SellingPrice") or 0.0),

            step=0.01,

            format="%.2f",

            key=f"edit_selling_price_{index}",

        )

    edit_expiry_date = st.date_input(

        "Expiry Date",

        value=item.get("ExpiryDate") or date.today(),

        key=f"edit_expiry_date_{index}",

    )

    new_purchase_value = float(edit_quantity) * float(edit_purchase_price)

    st.info(f"Purchase Value: ₹{new_purchase_value:,.2f}")

    save_col, cancel_col = st.columns(2)

    with save_col:

        if st.button(

            "💾 Save Changes",

            type="primary",

            width="stretch",

            key=f"save_edit_{index}",

        ):

            if not edit_product_name.strip():

                st.error("Product Name is required.")

                return

            if not edit_batch_no.strip():

                st.error("Batch Number is required.")

                return

            item["ProductName"] = edit_product_name.strip()

            item["Barcode"] = edit_barcode.strip() or None

            item["BatchNo"] = edit_batch_no.strip()

            item["Quantity"] = float(edit_quantity)

            item["PurchasePrice"] = float(edit_purchase_price)

            item["SellingPrice"] = float(edit_selling_price)

            item["ExpiryDate"] = edit_expiry_date

            item["PurchaseValue"] = new_purchase_value

            st.session_state.stock_items[index] = item

            st.session_state.match_message = "✅ Stock item updated successfully."

            st.rerun()

    with cancel_col:

        if st.button("Cancel", width="stretch", key=f"cancel_edit_{index}"):

            st.rerun()





st.markdown('<div class="section-title">2. Stock Added</div>', unsafe_allow_html=True)

if not st.session_state.stock_items:

    st.info("No stock items added yet.")

else:

    for index, item in enumerate(st.session_state.stock_items):

        with st.container(border=True):
            col1, col2, col3, col4 = st.columns([2.8, 2.0, 2.0, .8])

            with col1:
                st.markdown(f"<div class='stock-name'>{item['ProductName']}</div>", unsafe_allow_html=True)
                st.markdown(
                    f"<div class='stock-meta'>Barcode: {item['Barcode'] or '-'} &nbsp;•&nbsp; Batch: {item['BatchNo']}</div>",
                    unsafe_allow_html=True,
                )
                if item["ProductStatus"] == "EXISTING":
                    st.markdown("<span style='color:#15803d;font-size:.7rem;font-weight:600;'>● EXISTING PRODUCT</span>", unsafe_allow_html=True)
                else:
                    st.markdown("<span style='color:#b45309;font-size:.7rem;font-weight:600;'>● NEW PRODUCT</span>", unsafe_allow_html=True)

            with col2:
                st.markdown(
                    f"<div class='stock-meta'>QTY</div><b>{item['Quantity']:,.3f}</b><br>"
                    f"<span class='stock-meta'>Purchase ₹{item['PurchasePrice']:,.2f} &nbsp;•&nbsp; Selling ₹{item['SellingPrice']:,.2f}</span>",
                    unsafe_allow_html=True,
                )

            with col3:
                st.markdown(
                    f"<div class='stock-meta'>EXPIRY</div><b>{item['ExpiryDate']}</b>",
                    unsafe_allow_html=True,
                )
                st.metric("Purchase Value", f"₹{item['PurchaseValue']:,.2f}")

            with col4:
                if st.button("✏️", key=f"edit_{index}", width="stretch", help="Edit stock item"):
                    edit_stock_item_dialog(index)
                if st.button("🗑️", key=f"remove_{index}", width="stretch", help="Remove stock item"):
                    remove_stock_item(index)
                    st.rerun()

st.divider()

# TOTAL

total_purchase_value = sum(

    item["PurchaseValue"] for item in st.session_state.stock_items

)

st.markdown('<div class="section-title">3. Stock Summary</div>', unsafe_allow_html=True)

col1, col2 = st.columns(2)

with col1:

    st.metric("Number of Products", len(st.session_state.stock_items))

with col2:

    st.metric("Total Purchase Value", f"₹{total_purchase_value:,.2f}")

st.divider()



st.markdown('<div class="section-title">Available Funds</div>', unsafe_allow_html=True)

st.caption("Latest open cash-drawer balances across users.")

if available_funds is None:

    st.warning("Funds could not be verified. Stock submission is unavailable.")

else:

    funds_col1, funds_col2, funds_col3 = st.columns(3)

    funds_col1.metric("Cash in hand", f"₹{cash_in_hand:,.2f}")

    funds_col2.metric("Cash in bank", f"₹{cash_in_bank:,.2f}")

    funds_col3.metric("Combined balance", f"₹{available_funds:,.2f}")



# SUBMIT

st.markdown('<div class="section-title">4. Submit for Admin Approval</div>', unsafe_allow_html=True)





# SUBMIT STOCK FOR ADMIN APPROVAL

def submit_stock_for_approval():

    if not st.session_state.stock_items:

        st.error("Please add at least one stock item.")

        return

    # Use the shared PostgreSQL engine from database.database

    try:

        cash_in_hand, cash_in_bank = get_available_funds()

        available_funds = cash_in_hand + cash_in_bank

        total_purchase_value = sum(

            item["PurchaseValue"] for item in st.session_state.stock_items

        )

        if available_funds <= total_purchase_value:

            st.error(

                "Cannot submit this stock entry: combined cash and bank balance "

                f"(₹{available_funds:,.2f}) must be greater than the purchase "

                f"value (₹{total_purchase_value:,.2f})."

            )

            return



        with engine.begin() as conn:

            # Create Manager Stock Entry

            header_sql = text("""

                INSERT INTO "ManagerStockEntry"

                (

                    "EnteredBy",

                    "TotalPurchaseValue",

                    "Status"

                )

VALUES

                (

                    :entered_by,

                    :total_purchase_value,

                    'PENDING'

                )

RETURNING "ManagerStockEntryID"

            """)

            result = conn.execute(

                header_sql,

                {

                    "entered_by": int(user["UserID"]),

                    "total_purchase_value": total_purchase_value,

                },

            )

            manager_stock_entry_id = result.scalar_one()

            # Insert each stock item

            item_sql = text("""

                INSERT INTO "ManagerStockEntryItems"

                (

                    "ManagerStockEntryID",

                    "ProductID",

                    "ProductName",

                    "Barcode",

                    "BatchNo",

                    "Quantity",

                    "PurchasePrice",

                    "SellingPrice",

                    "ExpiryDate",

                    "PurchaseValue",

                    "ProductStatus"

                )

                VALUES

                (

                    :entry_id,

                    :product_id,

                    :product_name,

                    :barcode,

                    :batch_no,

                    :quantity,

                    :purchase_price,

                    :selling_price,

                    :expiry_date,

                    :purchase_value,

                    :product_status

                )

            """)

            for item in st.session_state.stock_items:

                conn.execute(

                    item_sql,

                    {

                        "entry_id": manager_stock_entry_id,

                        "product_id": item["ProductID"],

                        "product_name": item["ProductName"],

                        "barcode": item["Barcode"],

                        "batch_no": item["BatchNo"],

                        "quantity": item["Quantity"],

                        "purchase_price": item["PurchasePrice"],

                        "selling_price": item["SellingPrice"],

                        "expiry_date": item["ExpiryDate"],

                        "purchase_value": item["PurchaseValue"],

                        "product_status": item["ProductStatus"],

                    },

                )

        # Clear current stock entry after successful commit

        st.session_state.stock_items = []

        st.success(

            f"✅ Stock submitted successfully. " f"Entry No: {manager_stock_entry_id}"

        )

        st.info("The stock is now PENDING Admin approval.")

    except Exception as e:

        st.error("Unable to submit stock entry.")

        st.exception(e)





# SUBMIT BUTTON

if st.session_state.stock_items:

    total_purchase_value = sum(

        item["PurchaseValue"] for item in st.session_state.stock_items

    )

    st.metric("Total Purchase Value", f"₹{total_purchase_value:,.2f}")

    st.caption("This amount will be checked against the purchase " "invoice by Admin.")

    can_submit = available_funds is not None and available_funds > total_purchase_value

    if available_funds is not None and not can_submit:

        st.warning(

            "Combined cash and bank balance must be greater than the purchase value "

            "to submit this stock entry."

        )

    if st.button(

        "📤 Submit for Admin Approval",

        type="primary",

        width="stretch",

        disabled=not can_submit,

    ):

        submit_stock_for_approval()

else:

    st.info("Add stock items above before submitting.")

    if not st.session_state.stock_items:

        st.error("Please add at least one stock item.")

    else:

        st.success("✅ Stock entry is ready for Admin approval.")

        st.info("Database staging/approval will be connected next.")
